---
- hosts: localhost
  tasks:
  - name: add authorized keys
    authorized_key:
      user: root
      state: present
      key: '{{ item }}'
    with_file:
      - public_keys/xikai.pub
      - public_keys/member-rsync.pub
      - public_keys/yangxionghai.pub