- hosts: localhost
  roles:
    - nginx
  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "member-sso-web.kptest.cn"
        root: "/srv/member-sso-web/dist"
        access_log: "/var/log/nginx/member-sso-web.kptest.cn.access.log"
        error_log: "/var/log/nginx/member-sso-web.kptest.cn.error.log"
        index: "index index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        extra_parameters: |
          location / {
              try_files $uri /index.html;
              proxy_set_header   X-Forwarded-For $remote_addr;
              proxy_set_header   Host $http_host;
          }
      - listen: "80"
        server_name: "member-sso-web.kpmember.cn"
        root: "/srv/member-sso-web/dist"
        access_log: "/var/log/nginx/member-sso-web.kpmember.cn.access.log"
        error_log: "/var/log/nginx/member-sso-web.kpmember.cn.error.log"
        index: "index index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        extra_parameters: |
          location / {
              try_files $uri /index.html;
              proxy_set_header   X-Forwarded-For $remote_addr;
              proxy_set_header   Host $http_host;
          }