---
supervisor_config_path: /etc/supervisor

# A list of `program`s Supervisor will control. Example commented out below.
supervisor_programs: []
  # - name: 'apache'
  #   command: apache2ctl -c "ErrorLog /dev/stdout" -DFOREGROUND
  #   state: present
  #   configuration: |
  #     autostart=true
  #     autorestart=true
  #     startretries=1
  #     startsecs=1
  #     redirect_stderr=true
  #     stderr_logfile=/var/log/apache-err.log
  #     stdout_logfile=/var/log/apache-out.log
  #     user=root
  #     killasgroup=true
  #     stopasgroup=true

supervisor_inet_http_server_enable: false
supervisor_inet_http_server_port: '0.0.0.0:9001'

supervisor_user: root
supervisor_password: 'my_secret_password'