- hosts: localhost
  roles:
    - nginx
    - php
    - php-swoole
    - php-xhprof
  vars:
    php_version: '7.2'
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "demo-web.dadi01.com"
        root: "/srv/demo-web/dist"
        access_log: "/var/log/nginx/demo-web.access.log"
        error_log: "/var/log/nginx/demo-web.error.log"
        index: "index index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        extra_parameters: |
          location / {
              proxy_set_header   X-Forwarded-For $remote_addr;
              proxy_set_header   Host $http_host;
          }
      - listen: "80"
        server_name: "demo-api.dadi01.com"
        root: "/srv/demo-api/public"
        access_log: "/var/log/nginx/demo-api.access.log"
        error_log: "/var/log/nginx/demo-api.error.log"
        index: "index index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        extra_parameters: |
          location / {
              try_files $uri $uri/ /index.php$is_args$args;
          }
          location ~ \.php$ {
              include snippets/fastcgi-php.conf;
              fastcgi_pass unix:/dev/shm/php-fpm.sock;
          }