- name: Add BinTray deb repository
  become: yes
  get_url:
     url: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+xenial_all.deb
     dest: /tmp/zabbix-release_4.0-2+xenial_all.deb

- name: dpkg install zabbix-release
  shell: dpkg -i /tmp/zabbix-release_4.0-2+xenial_all.deb

- name: Install zabbix-agent
  apt: name=zabbix-agent state=present update_cache=yes

- name: configure zabbix-agent
  template: src=zabbix_agentd.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify:
     - restart zabbix-agent

- name: zabbix-agent started
  service: name=zabbix-agent state=started enabled=yes